### ISSUE TITLE
Memory allocation fail

### ISSUE THREAD

**Issue by djhocking** [kaskr/adcomp#132]
I am working with Jim Thorson on a spatiotemporal model over all large area with a huge number of nodes. The model runs okay and coverges, but when I run the `sdreport(obj)` I get a memory issue:

```
Error in f(x, order = 1) : 
  Memory allocation fail in function 'EvalADFunObject'
```

The network I'm using is very large (nodes = 11,172, years = 39). It seems like the memory issue is with R and not my computer (if it were my computer I could run it on a server with tons of RAM). If this is an issue with memory limits in R, is there any way around this to approximate uncertainty in the parameter estimates (particularly the predictions of abundance)?

**Comment by kaskr** [comment]
R should have access to all of your machine's RAM (unless 'ulimit' has been set to limit memory usage)... You probably run out of memory because you are ```ADREPORT```ing a large number of variables? A solution could then be to call sdreport multiple times each reporting a smaller chunk of variables (note: the Hessian need not be re-calculated each time as it can be passed to sdreport).

**Comment by djhocking** [comment]
That worked. Thanks for the help.

**Comment by kaskr** [comment]
After first nlminb-optimization run:
```h <- optimHess(opt1$par, obj1$fn, obj1$gr)```
Pass it to sdreport for first chunk:
```
obj1$env$data$flag <- 1 ## Assuming this enables first subset to report
SD1 = sdreport( obj1, hessian=h)
```
Second chunk:
```
obj1$env$data$flag <- 2 ## Assuming this enables second subset to report
SD2 = sdreport( obj1, hessian=h)
```
etc
