### ISSUE TITLE
namespace autodiff; in which context can it be used?

### ISSUE THREAD

**Issue by skaug** [kaskr/adcomp#142]
The namespace autodiff is a very useful and elegant addition to TMB.
It lets you calculate derivatives inside the c++ template, which
I am sure will find many non-standard applications in the future.

But, in which contexts can it be used? My guess is that 
1. If you use h = autodiff::hessian, the you are not allowed to take  $he() of the objective function in R
    because it would involve 4th order derivatives.
2. You are not allowed to use the "random" argument of MakeADFun

Are these correct? If so, I will write this in the docs.

Hans

**Comment by kaskr** [comment]
Actually, there are no direct limitations (except that it might use an
awful lot of memory). The new example 'laplace.cpp' demonstrates the
potential: By coding the Laplace approximation in the template you're
allowed to use the ```obj$he()``` from R (which involves up to 4th
order derivatives).

It is also perfectly OK to use the "random" argument in conjunction
with the autodiff namespace.

Note: All this is something we get 'for free' due to the generality of
the CppAD library.

**Comment by alexfun** [comment]
Can I please ask, what is the difference between the gradient obtained using autodiff within the cpp objective function, and obj$gr() from within R after the cpp file is compiled and 'made' using MakeADFun?
