### ISSUE TITLE
citation for timing comparison with BUGS

### ISSUE THREAD

**Issue by mebrooks** [kaskr/adcomp#162]
Hi,

In a manuscript, I would like to state that TMB is way faster than BUGS, but I don't want to go to the trouble of implementing my model in BUGS. Is there a paper published that does such a comparison? 

It seems that the examples Orange, Theta, and Nmix from the Bolker et al. (2013) MEE paper are timed in the Kristensen et al. (2015) JSS paper. Since the first paper shows that ADMB is faster than BUGS and the second paper shows that TMB is faster than ADMB, I guess by the transitive property, I can say that TMB is faster than BUGS. I'm assuming that most of my readers will be more familiar with BUGS than ADMB. So I was looking for a more direct route, but this will work if it's all I have.

thanks,
Mollie

**Comment by mebrooks** [comment]
Actually, I don't think we included the timings in the 2013 paper. That's why Arni submitted a follow up comment that included a table of timings for R, ADMB, and BUGS.

**Comment by arnima-github** [comment]
Yes, I submitted a brief follow-up (benchmark table and a short discussion) with the same authors as the original paper, but the editor rejected it because it didn't fit in any of the journal article types. I asked whether the relatively new journal might add a new article type called 'addendum'. The editor showed some interest in that, but at that point I was swamped with other tasks.
Thanks for bringing this up, Mollie. I'll resend it as 'addendum' this month, and see if the editor thinks it's publishable.

**Comment by mebrooks** [comment]
I went back to the addendum to get the timings for ADMB versus BUGS. If the speedup factors in Kristensen et al. (2015) are calculated as `time(ADMB)/time(TMB)`, then I think the speedup factors for TMB vs BUGS would be 276 for the Orange growth example, 472 for the Theta example, and 78.6 for the Nmix example.

**Comment by mebrooks** [comment]
Just to update this issue... I ended up making the link from BUGS to ADMB using Table 2 in this paper: Pedersen, M. W., Berg, C. W., Thygesen, U. H., Nielsen, A., & Madsen, H. (2011). Estimation methods for nonlinear state-space models in ecology. Ecological Modelling, 222(8), 1394-1400.
 
Thanks to Martin Pedersen for the tip.
