### ISSUE TITLE
Problem running mcmc:   missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by johnrsibert** [kaskr/adcomp#175]
This code

```
obj = MakeADFun(data,parameters,random=c("U"),DLL="issams")
obj$control=list(trace=1,eval.max=1,iter.max=2)

print("starting optimization-------------------------",quote=FALSE)
st=system.time(opt <- nlminb(obj$par,obj$fn,obj$gr)) #,control=obj$control))
print("finished optimization-------------------------",quote=FALSE)
print("Timings:")
print(st)
print(paste("Objective function value =",opt$objective))
sd.rep = sdreport(obj)
max.grad = max(sd.rep$gradient.fixed)
std = rbind(summary(sd.rep,select="fixed"),
            summary(sd.rep,select="report"))
print(paste("Number of parameters = ",length(opt$par),
            " Objective function value = ",opt$objective,
            " Maximum gradient component = ",max.grad,sep=""),quote=FALSE)
print(std)
print("Starting MCMC --------------------------------",quote=FALSE)
rwm = mcmc(obj=obj, nsim=50000, algorithm='RWM') 
```

produces the following output

```
[1] Number of parameters = 5 Objective function value = 247.377482806857 Maximum gradient component = 0.000205811807272721
                   Estimate   Std. Error
logFmsy       -1.807382e+00 4.684979e-01
logMSY         7.173542e+00 7.232773e-01
logsdlogProc  -1.295857e+00 8.854105e-02
logsdlogYield -7.541850e-01 7.765588e-02
logQ          -3.107129e+00 1.155079e+00
sdlogProc      2.736633e-01 2.423044e-02
sdlogYield     4.703938e-01 3.652885e-02
Q              4.472917e-02 5.166574e-02
MSY            1.304456e+03 9.434836e+02
Fmsy           1.640832e-01 7.687261e-02
r              3.281663e-01 1.537452e-01
K              1.589994e+04 1.601047e+04
[1] Starting MCMC --------------------------------
Error in if (log(runif(1)) < fn.new - fn.cur) { : 
  missing value where TRUE/FALSE needed
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Timing stopped at: 196.673 0.188 196.863 
> tail(warnings())
Warning messages:
1: In destructive_Chol_update(L, H, t) :
  Cholmod warning 'matrix not positive definite' at file ../Supernodal/t_cholmod_super_numeric.c, line 729
2: In destructive_Chol_update(L, H, t) :
  Cholmod warning 'matrix not positive definite' at file ../Supernodal/t_cholmod_super_numeric.c, line 729
3: In destructive_Chol_update(L, H, t) :
  Cholmod warning 'matrix not positive definite' at file ../Supernodal/t_cholmod_super_numeric.c, line 729
4: In destructive_Chol_update(L, H, t) :
  Cholmod warning 'matrix not positive definite' at file ../Supernodal/t_cholmod_super_numeric.c, line 729
5: In destructive_Chol_update(L, H, t) :
  Cholmod warning 'matrix not positive definite' at file ../Supernodal/t_cholmod_super_numeric.c, line 729
6: In destructive_Chol_update(L, H, t) :
  Cholmod warning 'matrix not positive definite' at file ../Supernodal/t_cholmod_super_numeric.c, line 729
```

**Comment by colemonnahan** [comment]
Hi @johnrsibert , I didn't see this b/c I'm not following issues here unless referenced. 

If you leave `random="U"` turned on in the object, then it's doing the LA at each iteration of the MCMC algorithm (I believe this is analogous to the `-mcmc2` flag in ADMB-RE). For some parameter combinations the LA fails, so the objective value returned isn't finite and that part of the MCMC code fails.

I suggest trying setting the U parameters to be fixed.

**Comment by johnrsibert** [comment]
Hi @colemonnahan 
Thanks for responding. I'm kind of a TMB newbie; this model is a port of a ADMB-RE model that I have been developing (https://github.com/johnrsibert/XSSA). I have been using the -mcmc2 flag to generate posteriors of the (non-random effect) parameters. The error in the TMB version seems to depend on the number of MCMC simulations, that is  10,000 seems to run to completion, but 50,000 produces the error.

The possibility of LA failure has occurred to me, too. The ADMB version reports some non PD comments in the Cholesky decomposition. My impression is that the model is not well determined by the data, but I'm not sure how to identify the problem.

Would "setting the U parameters to be fixed" (however that is done) produce posterior distribution of the other parameters?

Cheers,
John

**Comment by colemonnahan** [comment]
@johnrsibert I don't know the LA approach that well, so I can't say how ADMB-RE would compare to TMB for the same model. It's possible that Dave has added some more sophisticated error checks to his MCMC algorithm for when it does fail, and it catches that. Whereas mine does not (yet). The length of the chain makes sense: it probably fails in the tails and it might take a long time to get there with RWM.

Taking away the `random="U"` part of your model will indeed turn them into fixed effects and get posteriors for them. This would be equivalent to `-mcmc` in ADMB-RE instead of `-mcmc2`. The chain will definitely run faster per iteration this way (it's not doing the LA at each step), but it's not clear to me if it's more efficient in how many effective samples it generates per time (a more meaningful metric of performance for MCMC). It should also be more stable with respect to errors.

The NUTS algorithm is likely to be orders of magnitude more efficient than the RWM, so it's worth a try. I've also put more error checks into those.

See this thread https://github.com/kaskr/adcomp/issues/173 if you have any thoughts you'd like to contribute on functionality for MCMC in TMB.

Thanks and good luck!
-Cole

**Comment by johnrsibert** [comment]
@colemonnahan I gave NUTS a try without much joy:
```
rwm = mcmc(obj=obj, nsim=50000, algorithm="NUTS")
MCMC NUTS: Madapt not specified, defaulting to half of nsim
MCMC NUTS: No eps given so using dual averaging during first 25000 steps.
Error in destructive_Chol_update(L, H, t) : 
  CHOLMOD factorization was unsuccessful
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

**Comment by colemonnahan** [comment]
@johnrsibert The NUTS algorithm takes very big steps during initialization and the first part of the warmup, if `eps` is adapted. If you're having LA errors this will exacerbated  because it's basically going to try to jump into the tails.

Again, try turning off the LA for the U parameter vector and that should help quite a bit. Alternatively you could set `eps` to something small and slowly increase it.

**Comment by cnot003** [comment]
@colemonnahan I have been translating a model from ADMB to TMB. The model successfully estimates the parameters and objective function value through ML using nlminb, however it does produce the warning:

Warning messages:
1: In nlminb(obj$par, obj$fn, obj$gr, lower = lower, upper = upper) :
  NA/NaN function evaluation

Although nlminb handles the NA/NaN function evaluations, run_mcmc does not seem to. In this situation when the mcmc sampler runs into NA/NaN values the sampling procedure ceases to select new samples.

Adding some functionality to allow bounding the parameters may help prevent this in certain situations.

Can you provide me with information on the further arguments to be passed to the algortihm, in the help it states:

...	
Further arguments to be passed to the algorithm. See help files for the samplers for further arguments.

What help files are being refereed to here?

Thanks
Chris

**Comment by colemonnahan** [comment]
Hi @cnot003 

If you're using NUTS ( and you should be), then I just mean do `?mcmc.nuts` to get the arguments for that algorithm. I should make that more clear in the help file.

NUTS should handle NA/NaN values by rejecting the trajectory and trying a new momentum draw. I had a model that was giving me some NaN values so I tried to put that in there, but I must have missed a case. My strategy was to catch the NaN and replace it with Inf, which would cause HMC, NUTS, and RWM to reject that state. https://github.com/kaskr/adcomp/blob/master/TMB/R/mcmc.R#L51.

It can also be that the dual averaging algorithm can have NaN for its arguments, and in that case we want to make the step size smaller, so I do this: https://github.com/kaskr/adcomp/blob/master/TMB/R/mcmc.R#L478
and
https://github.com/kaskr/adcomp/blob/master/TMB/R/mcmc.R#L450

Which case do you think your're running into? Error handling is probably the first reason these functions are still marked as BETA. We also would expect more of these errors during the warmup phase, because it will try step sizes that are too big and diverge away from the region of high posterior density. That's fine, since we discard those samples anyway. If you're getting that sporadically after warmup you should make `delta` bigger (try 0.9). 

The best approach is to have a completely defined surface, and if bounding parameters gets you there then I'd definitely recommend that. Unfortunately we haven't put bound capabilities on the R side, so you need to do it in the .cpp file, using a logistic or log transform as needed.

Let me know how it goes.

**Comment by kaskr** [comment]
See #173
