### ISSUE TITLE
Nested optimization

### ISSUE THREAD

**Issue by wzhang721** [kaskr/adcomp#186]
Hi,
I am now trying to solve a minimization problem using 'TMB' but I do not know the explicit form of the objective function, which contains another minimization problem. In more detail here. Suppose we have an equation F(theta, s)=0, which is difficult to solve and also we have got a function f(s), where s should be a function of theta, then we hope to minimize f over theta. 

This is an optimization within optimization problem. Currently, I am doing like this: for the evaluation of f over each value of theta, I am using TMB to solve the equation (as an optimization) to get the solution shat and then calculate f(shat), as an approximation to f(s). Using R optimizer 'nlm' can minimize f over theta, but it is not an ideal approach since TMB does nothing with the outer optimization.    

Can this problem solved by TMB? Many people say it could be, but I still have no idea with it:-(.  

Many thanks for your help!!

Joey

**Comment by skaug** [comment]
I do not think there any examples or "best practice" in TMB for the general case. 
The best way to proceed depends on i) the dimensions of s and theta
ii) how "hard" the inner problem  F(theta, s)=0 is. 

If solving  F(theta, s)=0 can be done using Newton's method you can adapt the
example laplace.cpp in tmb_examples. This is a nested optimization problem.

If this fails I suggest to treat the problem as constrained optimization jointly in
the variables (theta,s) with
- objective function: f(s)
- constraint: F(theta, s)=0

 There is an R package "nloptr" that I believe can deal with such constraints. I have not tried
this approach myself, though.

Hans

**Comment by Joey1206** [comment]
Thanks very much, Hans. 

I think the inner problem F(theta, s)=0 is not hard since it is the gradient of another function - I chose to optimize this function to make the gradient F=0. I think this works very well solving the equation. Then using 'nlm' solves the outer optimization without any help from TMB.

 I will look into the laplace example to see whether it is possible to solve the outer problem using TMB as well in my case. And "nloptr" is another option - thanks for reminding this.
