### ISSUE TITLE
R CHECK warnings

### ISSUE THREAD

**Issue by lpantano** [kaskr/adcomp#233]
Hi,

thanks in advance for the time to maintain this super nice package. I am very new to compile C code in R so sorry if this is stupid.

My collaborator and I  introduced `objective_function` in Cpp to be use with `gamlss`. here is the code for that: https://github.com/lpantano/isomiRs/blob/cpp/src/LQNO_DE.cpp

I got it compiled, but I am having a warning during R CHECK:

```
* checking compiled code ... WARNING
File ‘isomiRs/libs/LQNO_DE.so’:
  Found ‘_abort’, possibly from ‘abort’ (C)
    Object: ‘LQNO_DE.o’
File ‘isomiRs/libs/LQNO_DE.so’:
  Found non-API call to R: ‘R_RunExitFinalizers’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor the system RNG.
Compiled code should not call non-API entry points in R.
```

I think it comes from `TMB.h`, but not sure how to work around. I am with R 3.4, TMB  1.7.10, Rcpp 0.12.1.

I don't know if you have any hints to where to start to fix this. Thanks anyway!

**Comment by kaskr** [comment]
To get a package through `R CMD check` without warnings or (significant) notes please follow the steps in
https://github.com/kaskr/adcomp/wiki/Development#distributing-code.
Note that you do not need a `Makefile` in the src folder.

**Comment by lpantano** [comment]
Hi Kasper, 

thabks gor the tip. I am using the version from CRAN. I discovered that with the Makefile I got the warnings, but not if I remove it.

It seems there is a difference how the code get compiled with TMB::compile function and without.

The main reason I used the Makefile is because I'll have multiple CPP files, each of then with a different name that i'll use with makeadfun.

Do you know how to get this done? I looked at https://github.com/kaskr/adcomp/issues/43 and it seemed makefile worked at some point but not now.

Thanks a lot!

**Comment by kaskr** [comment]
Instructions https://github.com/kaskr/adcomp/wiki/Development#distributing-code are now updated so that it should be clear (?) how you can modify `TMB:::compile` in your Makefile to pass the checks.

Note however, that if you are planning to submit your package to CRAN there could be some caveats with the 'Makefile-approach'. Probably, you'll need a windows specific version `Makefile.win` (?). Secondly, using multiple templates your package will blow up in binary size which the CRAN maintainers do not appreciate.

You may want to consider the simpler alternative of having just one main template function say `main.cpp` (no Makefile required):

```cpp
#include <TMB.hpp>

template<class Type>
Type objective_function<Type>::operator() ()
{
  DATA_STRING(model_type);
  if (model_type == "model1") {
    #include "model1.h"
  } else
  if (model_type == "model2") {
    #include "model2.h"
  } else {
    error ("Unknown model type")
  }
  return 0;
}
```

Then put your different models in files `model1.h` and `model2.h`. This way you'll only use a single compilation unit for multiple models hence the package binary size will be reduced. The model type is selected from R at runtime by e.g.:

```
data$model_type <- "model1"
```

**Comment by lpantano** [comment]
Hi!

thanks a lot for the top. I think you last advice using the same file the two models the best approach! This is very helpful! 

Thanks a lot!

**Comment by deoclecioamorim** [comment]
Hello!
I did this using TMB 1.9.2 and 4.2.2 for two simple models on windows and the dlls were around 40Mb. How do I reduce the size of dlls. I tried the glmmTMB approach and the dlls were too big

**Comment by deoclecioamorim** [comment]
Hello!
I did this using TMB 1.9.2 and 4.2.2 for two simple models on windows and the dlls were around 40Mb. How do I reduce the size of dlls. I tried the glmmTMB approach and the dlls were too big
