### ISSUE TITLE
Avoiding under/overflow in mixture models

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#236]
Hi all,

I think mixture models are pretty common, where the likelihood of data is the sum of the likelihood across multiple components.  This sum is done in natural space (not log space) so numerical under/overflow is common.  I have just confirmed a simple solution using a custom CPP function `logsum`:

```cpp
// Function for taking two log-values, adding them in natural space, and returning its log
template<class Type>
Type logsum( Type x, Type y ){
  Type mid = (x+y)/2;
  return log(exp( x-mid ) + exp( y-mid )) + mid;
}
```

where this is more numerically stable than simply doing `log( exp(x)+exp(y) )`.  My questions are:

1.  Is it useful enough to add `logsum` to TMB cpp code or CPPAD?
2.  Is there a better solution to this problem that I'm missing?

Jim

**Comment by skaug** [comment]
I agree that this would be a very useful function to have. However it seems that
the convention is to use max = max(x,y) rather than "mid":

https://en.wikipedia.org/wiki/LogSumExp

There is a "max" function in TMB, which I assume is differentiable, but since it
relies on cppad code I cannot really figure out if there is an approximation involved.
So, maybe "mid" is a simpler solution.

**Comment by kaskr** [comment]
There is a `logspace_add` in TMB - see:

http://kaskr.github.io/adcomp/group__special__functions.html

It is formally equivalent to the R function

```
logspace_add <- function(logx, logy) {
    pmax (logx, logy) + log1p (exp (-abs (logx - logy)))
}
```

It is accurate over the entire range. For instance you get

```
> logspace_add(-100, 0)
[1] 3.720076e-44
```

while other implementations would return 0.

**Comment by James-Thorson** [comment]
Thanks Kasper!  I'm testing it now, and always appreciate learning new numerical tricks.
