### ISSUE TITLE
Function to cleanup TMB model files after failed compile?

### ISSUE THREAD

**Issue by colemonnahan** [kaskr/adcomp#239]
@kaskr is there a function to clean files when working on developing a model? What I find happens is as I 
 make changes to, and compile my model, the .o and .dll files do not always get overwritten. In this case, I can't delete the .o and .dll files manually, nor can I dynamically unlink the model. Sometimes I have to close R to release the dll, delete it, then restart R and recompile to fix it. 

Is there a way around this? What is your workflow when building a new model and making lots of mistakes?

I was thinking a function something like this:

````
clean.TMB.files <- function(model.path=getwd()){
  o <- paste0(model.path,'.o')
  dll <- paste0(model.path, '.dll')
  tryCatch(expr=dyn.unload(dynlib(model.path)), error=function(cond){x=3})
  if(file.exists(dll)) trash <- file.remove(dll)
  if(file.exists(o)) trash <- file.remove(o)
}
````

but fixed to handle more cases and check whether the files could be removed. Then you just run clean.TMB.files('model') before compiling and never have that issue.

Thoughts? Better way to avoid or fix this issue?

**Comment by kaskr** [comment]
On Windows you get 'permission denied' when deleting a loaded DLL file. The `TMB:::compile` takes care of this by

```r
    if (.Platform$OS.type == "windows") {
        tr <- try(dyn.unload(dynlib(libname)), silent = TRUE)
        if (!is(tr, "try-error")) 
            cat("Note: Library", paste0("'", dynlib(libname), 
                "'"), "was unloaded.\n")
    }
```

which is essentially what you have in `clean.TMB.files`. You should see `Note: Library ... was unloaded` during compilation - otherwise it's an indication that something went wrong.

The file `tmb_syntax/test_reload.R` tests that the development cycle (change/reload) works. Please report if you can make the script fail on Windows.

**Comment by colemonnahan** [comment]
The reload test worked for me, and I can't seem to reproduce the issue I was having earlier. If it happens again I'll be more careful about noting my workflow and see if I can reproduce it and share. If so I'll reopen this issue for further guidance.  Thanks!
