### ISSUE TITLE
Passing/converting PARAMETER_VECTOR(u) to legacy C code as a double or const double *

### ISSUE THREAD

**Issue by swihart** [kaskr/adcomp#241]
My research involves GLMMs with non-standard random effects distributions.  One such distribution I would like to use is an alpha-stable distribution from [libstable](https://www.jstatsoft.org/article/view/v078i01)'s  `stable_pdf()`.  From what I can tell the code is written in C and requires a `const double* u` to be passed as the second argument.  I've tried numerous things trying to convert PARAMETER_VECTOR(u) to a `const double* u`, such as:

`stable_pdf(dist,  reinterpret_cast<double*> (&u[0]), Nu, pdf, NULL);` 

to no avail.  I am a novice C programmer, but a proficient R programmer.

I wanted your input on how to proceed.  I thought of two options but am open to any advice you could give:

  *  Re-write libstable to take `Type` in templates
  *  Use some function that can temporarily pass values of a PARAMETER_VECTOR(u) to a function requiring (const) double* -- (if so, what is the function and may I be pointed to an example usage)

Thanks!

**Comment by kaskr** [comment]
* The idea of casting `PARAMETER_VECTOR` to `double*` would throw away
  derivative information which is not what you want.
* The idea of replacing double with Type and let TMB do the rest,
  works only for simple functions with a fixed computational
  graph. For complex adaptive algorithms (such as alpha stable
  distributions) the approach doesn't work because the computational
  graph changes between function evaluations.

There are two possible solutions:

1. If the family of alpha stable distributions is closed under
   differentiation you can link in the libstable compiled code.  Same
   approach as used to define `ppois` here:
   https://github.com/kaskr/adcomp/blob/master/TMB/inst/include/atomic_math.hpp#L322
2. If you don't know the derivatives of the family you can use forward
   mode AD to get the derivatives. However, this requires you are able
   to isolate the entire source code of the algorithm and convert all
   functions to C++ template functions. Many TMB special functions are
   generated this way, e.g.
   https://github.com/kaskr/adcomp/blob/master/TMB/inst/include/tiny_ad/atomic.hpp#L30
   A complete example is here:
   https://github.com/kaskr/adcomp/blob/master/tmb_examples/adaptive_integration.cpp
   The main obstacle with libstable is that it depends on gsl which is
   huge. Converting all gsl functions to C++ templates would not be
   feasible.
