### ISSUE TITLE
Compilation error with compile(); no errors with system() command

### ISSUE THREAD

**Issue by ksint** [kaskr/adcomp#284]
I am encountering a strange compilation error with the sam example. Any help is appreciated. Thanks!

```
> #download.file("https://github.com/kaskr/adcomp/archive/master.zip", "adcomp-master.zip")
> #unzip("adcomp-master.zip")
> setwd("adcomp-master/tmb_examples")
> source("sam.R")
C:/PROGRA~1/R/R-35~1.1/etc/x64/Makeconf:230: warning: overriding commands for target `.m.o'
C:/PROGRA~1/R/R-35~1.1/etc/x64/Makeconf:223: warning: ignoring old commands for target `.m.o'
C:/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG -IC:/Users/ksint/R/WIN-LI~1/3.5/TMB/include -IC:/Users/ksint/R/WIN-LI~1/3.5/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_sam  -DTMB_LIB_INIT=R_init_sam          -O2 -Wall  -mtune=generic -c sam.cpp -o sam.o
In file included from sam.cpp:31:0:
C:/Users/ksint/R/WIN-LI~1/3.5/TMB/include/TMB.hpp:35:25: fatal error: R_ext/Print.h: No such file or directory
 #include <R_ext/Print.h>
                         ^
compilation terminated.
make: *** [sam.o] Error 1
Error in compile("sam.cpp") : Compilation failed
```
It seems to be not finding the `C:/PROGRA~1/R/R-35~1.1/include/R_ext/Print.h` file. Does it have to do with `-I"C:/PROGRA~1/R/R-35~1.1/include"` containing quotes?

However, if I run 
```
system("C:/Rtools/mingw_64/bin/g++  -I\"C:/PROGRA~1/R/R-35~1.1/include\" -DNDEBUG -IC:/Users/ksint/R/WIN-LI~1/3.5/TMB/include -IC:/Users/ksint/R/WIN-LI~1/3.5/RCPPEI~1/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_sam  -DTMB_LIB_INIT=R_init_sam          -O2 -Wall  -mtune=generic -c sam.cpp -o sam.o")
```
It completes without error and creates the sam.o object file.

I am using TMB 1.7,14 with R 3.5.1 and Rtools 3.5.0.4 on Windows 10 1804.

**Comment by ksint** [comment]
Adding 
```
Sys.setenv(PATH = paste("C:/Rtools/bin", Sys.getenv("PATH"), sep=";"))
Sys.setenv(BINPREF = "C:/Rtools/mingw_$(WIN)/bin/")
```
to my C:\Users\ksint\.Rprofile fixed my issue (from [https://stackoverflow.com/questions/47539125/how-to-add-rtools-bin-to-the-system-path-in-r](url))

It is strange though. I have `C:\Rtools\bin;C:\Rtools\mingw_64\bin;` under PATH in Environment Variables. Somehow the my other PATH directories including MiKTex, ADMB, cygwin, and/or imagemagick must have been conflicting. Hope this helps someone.

**Comment by ksint** [comment]
Strange..., with the Rtools/bin path added, ADMB no longer works.... I had to run this to get ADMB working. Any elegant way to resolve the conflicts between Rtools compiler and ADMB compiler? Thanks.

```
Sys.setenv(PATH = paste("C:/Program Files (x86)/ADMB/utilities/mingw64/bin", Sys.getenv("PATH"), sep=";"))
```

**Comment by arnima-github** [comment]
I was setting up TMB on a colleague's computer and had a similar error. Found this page when I searched for the error message:

`fatal error: R_ext/Print.h: No such file or directory`

The culprit was a directory `C:\Program Files\OpenSSH\bin` that contained `sh.exe`. I believe TMB uses Rtools `make` that crashes if a non-Rtools `sh.exe` is earlier in the PATH.

To solve this and build TMB models, I can choose between several options:
1. Delete or rename `sh.exe` inside `OpenSSH\bin`
2. Move the `OpenSSH\bin` entry towards the end of the PATH, so it appears later than `Rtools\bin`
3. Remove the `OpenSSH\bin` entry from the PATH
4. Use a short PATH when working with TMB.
5. Something even more creative :)

This can happen with any software that ships with `sh.exe` so the list above is for general troubleshooting.

This problem should not be related to ADMB. Users should be able to build ADMB and TMB models without problems, see AD Studio (https://github.com/admb-project/adstudio).
