### ISSUE TITLE
"posfun" command for cpp declaration of model

### ISSUE THREAD

**Issue by ghost** [kaskr/adcomp#7]
Hi all,

Just a quick note that many state-space implementations require a function similar to "posfun" in ADMB, where a scalar of class Type is returned unchanged if above a certain threshold, but is returned at the threshold if below the threshold, and where the objective function is modified to penalize instances where it is below the threshold.

For example, an implementation of a state-space theta-logistic model requires posfun if using a lognormal process error (rather than the normal process error here:
https://groups.nceas.ucsb.edu/non-linear-modeling/projects/theta/ADMB/theta.tpl)

Cheers,
Jim

**Comment by bbolker** [comment]
Can we please re-open this?  It still seems to be a bit of a problem with TMB version 1.1.1 ... 

* causes a segfault  (32-bit Ubuntu, R devel 2015-07-29 r68752)
* *seems* OK on MacOS 64-bit, R 3.2.2

@James-Thorson : can you comment on what "doesn't work" means in your context?  Was it a segfault, or was the answer wrong (we haven't spent enough time staring at your code to know what answer it should be giving ...)?

James Thorson's code got a bit mangled so I'm re-posting it here with better formatting ... 

```
#include <TMB.hpp>

template<class Type>
Type posfun(Type x, Type eps, Type &pen){
    pen += CppAD::CondExpLt(x,eps,Type(0.01)*pow(x-eps,2),Type(0));
    return CppAD::CondExpGe(x,eps,x,eps/(Type(2)-x/eps));
}

template<class Type>
Type objective_function<Type>::operator() ()
{
DATA_SCALAR(eps);
 DATA_VECTOR(x);

 PARAMETER(p);
 PARAMETER(Dummy);
 Type pen;
 pen=0;

 Type nll;
 nll=0;

 Type var;
 var = p*(1-p);
 var = posfun(var, eps, pen);
 nll += pen;

 nll += -sum( dnorm(x, p, sqrt(var),true) );
 nll += -dnorm(Dummy, Type(0.0), Type(1.0), true);
 return nll;

}
```

**Comment by kaskr** [comment]
@bbolker I have trouble reproducing the segfault on 32 bit ubuntu with R-3.0.1. Could you confirm that you get a crash by 1. checking out the branch 'posfun'. 2. install TMB from that branch. 3. Run posfun example from tmb_examples ?

**Comment by bbolker** [comment]
hmm, can't reproduce now ... under 

```
R Under development (unstable) (2015-07-29 r68752)
Platform: i686-pc-linux-gnu (32-bit)
Running under: Ubuntu precise (12.04.5 LTS)

[snip]

other attached packages:
[1] TMB_1.1-1

loaded via a namespace (and not attached):
[1] compiler_3.3.0  Matrix_1.2-2    tools_3.3.0     grid_3.3.0     
[5] lattice_0.20-33
```

**Comment by bbolker** [comment]
Coming back here to post a link to the [ADMB posfun documentation](http://api.admb-project.org/group__misc.html#gacbc09bc0adfa8bf57862175815a8a1fa), and to explain a little bit more about what `posfun()` does/is supposed to do (since I had to figure it out for myself). The point of `eps` is *not* to guarantee that all values are greater than `eps`; it's to guarantee that values *above* `eps` are unchanged, and values between `eps` and -infinity are smoothly adjusted to be between 0 and eps.

May I suggest that this function be added as built-in utility in TMB?  (Fancier versions could include a  bound other than zero and a 'sign' (greater than/less than) switch ...)   I could submit a PR if requested ...

```
 curve(ifelse(x<eps,eps/(2-x/eps),x),-2e-3,2e-3)
abline(v=c(0,eps),lty=2)
abline(a=0,b=1,lty=3)
```
![eps](https://user-images.githubusercontent.com/78918/84181008-73818980-aa56-11ea-936a-03d144b4249f.png)

**Comment by kaskr** [comment]
@bbolker
I'm sceptical about posfun. It seems to cause trouble when used to transform random effects (based on user reports) - and I'm not surprised: The second order derivative of posfun is not continuous. If used with the Laplace approximation one would expect that each call to posfun adds new discontinuities to the marginal likelihood. So, no - I don't think posfun should be in the main TMB distribution.

**Comment by kaskr** [comment]
@bbolker
I should have been more precise with 'something similar to posfun'. I'm assuming the purpose of posfun is to approximate the [positive part](https://en.wikipedia.org/wiki/Positive_and_negative_parts) `max(0,x)` by a smooth monotone function with an error controlled by `eps`. For this purpose my `f` above works just as well as `posfun`. However, it does not hold *exact* that `f(x)=x` for all `x>eps` (in contrast to posfun).

**Comment by fishfollower** [comment]
I think the new suggestion looks interesting and when implementing it, it could be made more robust for large values by using logspace_add (the function already in TMB). 

Example in R:

logspace_add <- function(a,b) pmax(a, b) + log1p(exp(pmin(a,b)-pmax(a, b)))
f <- function(x, eps=0.001)eps*logspace_add(x/eps,0)
library(numDeriv)
Df <- function(x)grad(f,x)
DDf <- function(x)grad(Df,x)
par(mfrow=c(1,3))
plot(f,-0.01,0.01, main=0)
plot(Df,-.01,0.01, main=1)
plot(DDf,-.01,0.01, main=2)

**Comment by johnrsibert** [comment]
There are indeed many ways. If your are willing to tolerate a third 
order polynomial between eps and zero, you can determine the values of 
the necessary coefficients by assuming the second derivative is zero at 
eps.

**Comment by bbolker** [comment]
Just back to mention that a TMB version of @fishfollower's suggestion above

```
template<class Type>
Type posfun(Type x, Type eps, Type &pen) {
  pen += CppAD::CondExpLt(x,eps,Type(0.01)*pow(x-eps,2),Type(0));
  return CppAD::CondExpGe(x,eps,x,eps*logspace_add(x/eps,Type(0)));
}
```

works fine with @James-Thorson's example above, even with random effects (presumably because the second derivative is now smooth).

**Comment by fishfollower** [comment]
I understood @kaskr's suggestion as a way to avoid the conditional expressions, so we could simple use: 

```
template<class Type>
Type posfunx(Type x, Type eps){
  return eps*logspace_add(x/eps,Type(0));
}
```

Does that not work?

**Comment by bbolker** [comment]
OK, I misunderstood.  I'm looking for a function with the following properties:

1. f(x) > 0 for all x
2. f(x) = x for x > eps
3. f'(x) and f''(x) are continuous everywhere (including at x=eps)

I now realize that @fishfollower was just refining @kaskr's suggestion, which instead of criterion 2 substitutes " f(x) ≈ x for x > eps (or, f(x) → eps as x → infinity)".

**Comment by bbolker** [comment]
OK, I worked it out.  If we use `eps / sum( (x-eps)^i/eps^i)` for `x<eps` and `x` for `x>eps`, if the summation runs from i=0 to i=n, then we have continuous derivatives up to order n.  Is there any point to going higher than `n=2` ... ?

**Comment by kaskr** [comment]
Strictly speaking, the gradient of the Laplace approximation requires `n=3` and the Hessian requires `n=4`.

**Comment by bbolker** [comment]
I might go ahead and make an example implementation of this. Should I do the whole `TMB_ATOMIC_VECTOR_FUNCTION` thing, or just code it as a simple function for now?

**Comment by kaskr** [comment]
@bbolker
OK, that looks like an improvement of the original posfun.

Reading your pdf document I was reminded of the fact that the original posfun adds a penalty to nll. That makes sense when box-constraining model parameters. However, for random effects it's not that simple... We must make sure that our specified model density (corresponding to nll) without data integrates to one, right? However, it seems to me that adding penalties messes up the normalizing constant.

Before considering implementation details of posfun, perhaps it's worth demonstrating on a simple simulation-reestimation example that you can make box constraints work on random effects using posfun? (I doubt it will work... Am I missing something?)

**Comment by bbolker** [comment]
Getting back to this ...  what kind of example do you suggest?  If the constraints aren't binding at the optimal solution (i.e. if the main purpose of `posfun` is to get us through/around bad patches of parameter space), then it should be OK ... @James-Thorson's example above "works", but I think the main purpose of that example was to show that the old `posfun` was grossly broken for random effects (because of the derivative characteristics), not that it would give a good/correct answers when the constraints were binding ...

**Comment by kaskr** [comment]
@bbolker 
That is exactly my problem: I cannot imagine any *random effect* examples for which posfun is useful!

> If the constraints aren't binding at the optimal solution (i.e. if the main purpose of posfun is to get us through/around bad patches of parameter space), then it should be OK ...

- You never really know if the 'bad patches' have insignificant probability measure.
- Even if they do I don't think you need posfun to stabilize the inner problem optimizer `TMB:::newton`.

Example: Consider integrating `dnorm(x) * (x > -1)` using the Laplace approximation corresponding to a 'bad patch' `x < -1` coded up using `posfun`. The constraint is non-binding so the Laplace approximation is the same as that of `dnorm(x)` - i.e. obviously wrong. I could have picked any other 'bad patch' on negative reals and the result would be the same. How do you decide whether the patch is insignificant in general? And what did I gain in my example above by using posfun to handle the constraint?

**Comment by MarkMaunder** [comment]
Did any solve this issue for the  state-space theta-logistic model using posfun with lognormal process error? I am using it and having convergence issues. The reason posfun is needed is because it is catch conditioned (catch is removed as known). Is using posfun with random effects just a bad idea and you have to estimate F as a random effect and fit to catch.

**Comment by kaskr** [comment]
@MarkMaunder 

> Is using posfun with random effects just a bad idea

Yes!

> The reason posfun is needed is because it is catch conditioned (catch is removed as known)

If I understand the problem correctly, there's a constraint on the state variable `log(B)` in that current catch must be smaller than current biomass `C < B`. Couldn't that be handled by transforming the state variable?
`U := log(B-C)`

(BTW: This discussion is more appropriate for tmb-users list...)
