### ISSUE TITLE
Good Hamiltonian MCMC code sitting around?

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#87]
Hi all,

I'd like to explore MCMC for comparison with bias correction (of random effects conditional on the MLE) or asymptotic standard error estimates (of fixed effects conditional on the data).  It seems like Hamiltonian or Langevin MCMC would leverage the cheap gradient computations that TMB provides.  

Does anyone have good MCMC code sitting around for Hamiltonian or Langevin MCMC?  There's a few starting points online, but I thought I'd ask before sinking more time in this.

cheers,
jim

**Comment by skaug** [comment]
Yes, it would certainly be nice to have R code for the no-U-turn sampler used by STAN. I know there is matlab code, but I have not found any R versions.

Hans

**Comment by colemonnahan** [comment]
I've been working through the NUTS paper and using a simple TMB example to try to get HMC working. I'm starting with the standard HMC and then going to try adding the adaptive L and then finally adaptive epsilon.

I'm very new to TMB (have only played with example models) so I would love any thoughts on coding practices or style guide I should be using. When it's ready I can merge the separate algorithms into the TMB source here on this repo (presumably that's the way you'd prefer), with some basic examples to demonstrate their use.

**Comment by kaskr** [comment]
Hi Cole,

There are no strict guidelines. However I do have som suggestions:

Add-on functionality like MCMC should	be isolated in a single file 'mcmc.R' including documentation and test example. Use 'tmbprofile.R' for inspiration: Your function should take 'obj' as input and rely on the function (obj$fn) and gradient (obj$gr).

I would prefer something like this
```mcmc <- function(obj, nsim=1, algorithm="NUTS",...)```
returning raw samples of the target 'exp(-fn(x))' by column.

It will be up to the user to construct 'obj' appropriately (e.g. with the Laplace approximation nested inside the sampler, or with certain parameters fixed).

Cheers,
Kasper

**Comment by colemonnahan** [comment]
Hi Kasper, this is exactly the kind of advice I was looking for. I'll take a look at `tmbprofile.R` and build the MCMC code as you suggest.

I'd like to keep the algorithm a little more general so those not using TMB could at least quickly adapt it, so I thought I'd try to write them as generic functions and then make wrappers for TMB which would then be easy to slot in future algorithms.

I'll keep working at this and make a pull request when I'm done. Can you please give me privileges? Thanks!

**Comment by kaskr** [comment]
OK, when you're done please send the pull request to branch kaskr/testing.

Thanks,
Kasper

**Comment by colemonnahan** [comment]
The branch `mcmc` now contains beta versions of the HMC and NUTS samplers. Please test them out and let me know of any issues. 

Also, I'll be continuing to add functionality and new algorithms to that branch as I go so keep checking back or make requests.

**Comment by skaug** [comment]
Sounds good. One thing one could do is to take examples from the STAN software.
Since STAN is running  NUTS it would provide verification of your algorithm
and give opportunity for timing comparisons.

Another thing: what to do about latent random variables? Your sampler only 
runs on the parameters, not the latent random variables (defined via "random" in TMB),
I think. This is actually nice, because the parameter space is typically low dimensional,
so judging convergence is easy. It would be possible to ad post-hoc step
to sample the latent random variables. Have you given this any thought?

Hans

**Comment by colemonnahan** [comment]
@skaug: Good idea. For now we can't do a direct comparison because I haven't added dual averaging, meaning the user must specify `eps`.  In general I think that's a great idea though and I'll add their key examples to my set and push them to TMB examples if so desired.

I honestly haven't given mixed models much thought, mostly because I don't use them. I was assuming that if a model had random effects the user would **not** set the model up with them as 'random' so they were treated as fixed effects in the sampler. (But admittedly I'm still learning TMB). What your talking about with doing the Laplace approximation over random effects in the chain is something I haven't thought about but sounds like a good thing to try. Then some post-hoc sampling of them, given each draw from the hyperparameters, seems reasonable. I guess something like a posterior predictive distribution. Does TMB have negative phases like ADMB, so that parameters can be fixed easily? 

Neal (2011) discusses how the nature of HMC does not always lend itself to efficient sampling of hierarchical models. He also talks about techniques like alternating steps of Gibbs sampling on the hyperparameters and then HMC on the random effects. That's beyond what I'm looking to do at the moment, particularly in a general sense. But maybe an advanced user could set that up themselves.

**Comment by colemonnahan** [comment]
@James-Thorson The HMC and NUTS code is now merged into the master branch. See `?mcmc` as a starting place. Let me know if you run into any issues.

**Comment by kaskr** [comment]
See #173
